Description of calc_RtR_prior
Home > eidors > solvers > calc_RtR_prior.m
calc_RtR_prior
PURPOSE
RtR = calc_RtR_prior(inv_model)
SYNOPSIS
function RtR_prior = calc_RtR_prior(inv_model)
DESCRIPTION
 RtR = calc_RtR_prior( inv_model )
 CALC_RtR_PRIOR: calculate image regularization prior
   R'*R (which is an estimate of the inverse of the covariance)
   Typically, the image prior is matrix n_elem x n_elem of the
   normalized a priori crosscorrelation FEM element values
 calc_RtR_prior can be called as
    RtR_prior= calc_RtR_prior( inv_model, ... )
 and will call the function inv_model.RtR_prior
 parameters to RtR_prior should be passed in the field
 inv_model.RtR_prior_function_name.parameters
 If inv_model.RtR_prior is a matrix, calc_RtR_prior will return that matrix,
 possibly correcting for coarse2fine
 if there exists a field inv_model.rec_model, then
   the prior is calculated on the rec_model rather than
   the fwd_model. This will not be done if
 inv_model.prior_use_fwd_not_rec= 1;
 RtR_prior    the calculated RtR regularization prior
 inv_model    is an inv_model structure
 If a function to calculate RtR_prior is not provided,
 RtR = R_prior' * R_prior;
CROSS-REFERENCE INFORMATION
This function calls:
eidors_msg EIDORS_MSG eidors progress and status messages
mdl_normalize MDL_NORMALIZE Check or set the normalize_measurements flag on a model.
eidors_cache EIDORS_CACHE Control eidors caching
This function is called by:
inv_solve_dual_mesh INV_SOLVE_DUAL_MESH using a coarse and fine mesh
np_inv_solve NP_INV_SOLVE inverse solver for Nick Polydorides EIDORS3D code
calc_JiRtRJt [JiRtRJt,iRtRJt] = calc_JiRtRJt(inv_model, varargin)
inv_solve_abs_GN_constrain Do Gauss Netwon Method with barrier to ensure positvity of the con
inv_solve_abs_GN_prior INV_SOLVE_ABS_GN_PRIOR inverse solver (WITH DIFFERENT PRIOR AT ITERATION!!!!!)
inv_solve_abs_core INV_SOLVE_ABS_CORE Absolute solver using a generic iterative algorithm
inv_solve_conj_grad INV_SOLVE_CONJ_GRAD inverse solver based on the CG
inv_solve_diff_GN_one_step INV_SOLVE_DIFF_GN_ONE_STEP inverse solver using approach of Adler&Guardo 1996
inv_solve_diff_kalman INV_SOLVE_DIFF_KALMAN inverse solver for difference EIT
inv_solve_mcmc NP_INV_SOLVE inverse solver for Nick Polydorides EIDORS3D code
inv_solve_time_prior INV_SOLVE_TIME_PRIOR inverse solver to account for time differences
nodal_solve NODAL_SOLVE inverse solver using approach of Adler&Guardo 1996
prior_movement PRIOR_MOVEMENT calculate image prior
calc_model_prior_test Verify model prior calcs
SUBFUNCTIONS
function RtR_prior = calc_from_R_prior(inv_model)
function inv_model = rec_or_fwd_model(inv_model);
SOURCE CODE
function RtR_prior = calc_RtR_prior(inv_model)
% RtR = calc_RtR_prior(inv_model)
% CALC_RtR_PRIOR: calculate image regularization prior
%   R'*R (which is an estimate of the inverse of the covariance)
%
%   Typically, the image prior is matrix n_elem x n_elem of the
%   normalized a priori crosscorrelation FEM element values
%
% calc_RtR_prior can be called as
%    RtR_prior= calc_RtR_prior(inv_model, ...)
%
% and will call the function inv_model.RtR_prior
% parameters to RtR_prior should be passed in the field
% inv_model.RtR_prior_function_name.parameters
%
% If inv_model.RtR_prior is a matrix, calc_RtR_prior will return that matrix,
% possibly correcting for coarse2fine
%
% if there exists a field inv_model.rec_model, then
%   the prior is calculated on the rec_model rather than
%   the fwd_model. This will not be done if
% inv_model.prior_use_fwd_not_rec= 1;
%
% RtR_prior    the calculated RtR regularization prior
% inv_model    is an inv_model structure
%
% If a function to calculate RtR_prior is not provided,
% RtR = R_prior' * R_prior;
% (C) 2005-2008 Andy Adler. License: GPL version 2 or version 3
% $Id: calc_RtR_prior.m 4833 2015-03-29 21:32:08Z bgrychtol-ipa $
inv_model = rec_or_fwd_model(inv_model);
if isfield(inv_model,'RtR_prior')
   if isnumeric(inv_model.RtR_prior)
      RtR_prior = inv_model.RtR_prior;
   else
      try inv_model.RtR_prior = str2func(inv_model.RtR_prior); end
      RtR_prior= eidors_cache( inv_model.RtR_prior, inv_model );
   end
elseif isfield(inv_model,'R_prior')
   RtR_prior = eidors_cache(@calc_from_R_prior, inv_model, 'calc_RtR_prior');
else
   error('calc_RtR_prior: neither R_prior nor RtR_prior provided');
end
if isfield(inv_model.fwd_model,'coarse2fine')
   c2f= inv_model.fwd_model.coarse2fine;
   if size(RtR_prior,1)==size(c2f,1)
%     we need to take into account coarse2fine - using a reasonable tol
      eidors_msg('calc_RtR_prior: using coarse2fine to model RtR');
      f2c= c2f'; %pinv(c2f,1e-6);
      RtR_prior=f2c*RtR_prior*c2f;
   end
end
function RtR_prior = calc_from_R_prior(inv_model)
   % The user has provided an R prior. We can use this to
   % calculate RtR= R'*R;
   if isnumeric(inv_model.R_prior)
      R = inv_model.R_prior;
   else
      try inv_model.R_prior = str2func(inv_model.R_prior); end
      R= eidors_cache( inv_model.R_prior, inv_model );
   end
   RtR_prior = R'*R;
function inv_model = rec_or_fwd_model(inv_model);
   if isfield(inv_model,'rec_model');
      use_rec_model = 1;
      try if inv_model.prior_use_fwd_not_rec== 1;
         use_rec_model = 0;
      end; end
      if use_rec_model
          % copy the normalize flag from the fwd_model to prevent warnings
         inv_model.rec_model = mdl_normalize(inv_model.rec_model, ...
                                       mdl_normalize(inv_model.fwd_model));
         inv_model.fwd_model= inv_model.rec_model;
         inv_model= rmfield(inv_model,'rec_model');
      end
   end