Description of left_divide
Home > eidors > algorithms > left_divide.m
left_divide
PURPOSE
[V] = left_divide(E,I,tol,pp,V);
SYNOPSIS
function [V] = left_divide(E,I,tol,pp,V)
DESCRIPTION
[V] = left_divide(E,I,tol,pp,V);
 Implements left division and overcomes many small inefficiencies
 of matlab's left division. Also uses conjugate gradients (for large problems).
E   = The full rank system matrix
I   = The currents matrix (RHS)
tol = The tolerance in the forward solution, e.g. 1e-5
 pp,V are old options from previous solver
CROSS-REFERENCE INFORMATION
This function calls:
eidors_msg EIDORS_MSG eidors progress and status messages
eidors_obj EIDORS_OBJ: 'constructor' to create a eidors structure
This function is called by:
demo_complex This demo function shows how the EIT problem can be formulated in a complex
eidors2d_demo1 EidorsDemo1 Demonstrates the use of 2D EIT Package with linear basis
fwd_solve_1st_order FWD_SOLVE_1ST_ORDER: data= fwd_solve_1st_order(img)
fwd_solve_higher_order Solve for voltages (nodes/electrodes) for a forward model.
jacobian_adjoint JACOBIAN_ADJOINT: J= jacobian_adjoint(img)
jacobian_adjoint_higher_order Find the Jacobian associated with an image (and forward model)
calc_GREIT_RM CALCULATE GREIT reconstruction matrix
SOURCE CODE
function [V] = left_divide(E,I,tol,pp,V)
%[V] = left_divide(E,I,tol,pp,V);
%
% Implements left division and overcomes many small inefficiencies
% of matlab's left division. Also uses conjugate gradients (for large problems).
%
%E   = The full rank system matrix
%I   = The currents matrix (RHS)
%tol = The tolerance in the forward solution, e.g. 1e-5
%
% pp,V are old options from previous solver
% (c) N. Polydorides 2003 % Copying permitted under terms of GNU GPL
% $Id: left_divide.m 3486 2012-07-04 09:02:48Z aadler $
if ~exist('tol'); tol = 1e-8; end
[n_nodes,n_stims] = size(I);
try
% V= E\I;
% This takes MUCH longer when you have  more vectors in I,
%  even if they are repeated. There must be some way to simplify
%  this to speed it up. Matlab's sparse operators really should
%  do this for you.
% TODO, Q&R should be cached somewhere
   [Q,R] = qr(I,0);
   rnotzeros = any(R~=0,2);
   Q= Q(:,rnotzeros);
   R= R(rnotzeros,:);
   V= (E \ Q)*R;
% TODO: Iteratively refine
%  From GH Scott: "once we have
%   computed the approximate solution x, we perform one step
%   of iterative refinement by computing the residual: r = Ax - b
%   and then recalling the solve routine to solve
%   Adx = r for the correction dx.
% However, we don't want to repeat the '\', so we implement
%   the underlying algorithm:
%   If A is sparse, then MATLAB software uses CHOLMOD (after 7.2) to compute X.
%    The computations result in  P'*A*P = R'*R
%   where P is a permutation matrix generated by amd, and R is
%   an upper triangular matrix. In this case, X = P*(R\(R'\(P'*B)))
%
% See also:
% http://www.cs.berkeley.edu/~wkahan/MxMulEps.pdf
% especially page 15 where it discusses the value of iterative refinement
%  without extra precision bits.  ALso, we need to enable
catch
   [lasterr_str,lasterr_id]= lasterr;
   if ~strcmp(lasterr_id , 'MATLAB:nomem')
      error(lasterr_str); % rethrow error
   end
   eidors_msg('Memory exhausted for inverse. Trying PCG',2);
   if nargin < 5
      sz= [size(E,1),n_stims];
      V = eidors_obj('get-cache', sz, 'left_divide_V');
      if isempty(V); V= zeros(sz); end
   end
   if isreal(E)
      U = cholinc(E,tol*100); L = U';
      cgsolver = @pcg;
   else %Complex
      [L,U] = luinc(E,tol/10);
      cgsolver = @bicgstab;
   end
   for i=1:n_stims
      [V(:,i),flag] = feval( cgsolver, E,I(:,i), ...
               tol*norm(I(:,i)),n_nodes,L,U,V(:,i));
   end
      eidors_obj('set-cache', sz, 'left_divide_V', V);
end
%%% OLD CODE
   % Cholesky solver. Gives poor results matching others
   % so we no longer use it
   if 0
       %Permute the rows and columns to make the factors sparser
       E = E(pp,pp);
       In = I(pp,:);
       rr(pp)=1:max(size(pp));  % this should be done only Once!
                                % actually much better just to do the
                                % renumbering when the mesh is generated!
       U = chol(E);
       q_c =  U' \ In;
       Vn = U \ q_c;
       %De-permute the result for Cholesky
       V = Vn(rr,:);
   end