Description of get_elem_volume
Home > eidors > models > get_elem_volume.m
get_elem_volume
PURPOSE
GET_ELEM_VOLUME: VOL = get_elem_volume(fwd_model, map_node)
SYNOPSIS
function VOL = get_elem_volume(fwd_model, map_node)
DESCRIPTION
 GET_ELEM_VOLUME: VOL = get_elem_volume(fwd_model, map_node )
 Calculate volume (or area) of each element in model
 If the model has a 'coarse2fine' element, then the
 returned VOL applies to the coarse matrix
 if map_node == 1, then calculated volumes are the volume fraction for each node
CROSS-REFERENCE INFORMATION
This function calls:
eidors_obj EIDORS_OBJ: 'constructor' to create a eidors structure
sparse SPARSE Create sparse matrix (EIDORS overload).
eidors_cache EIDORS_CACHE Control eidors caching
This function is called by:
calc_noise_params params = GREIT_noise_params(imdl, homg_voltage, sig_voltage)
dm_mk_fwd_model DM_MK_FWD_MODEL: create a fwd_model object using distmesh
analytic_2d_circle V = analytic_2d_circle(J, [s_h, s_i, b, a, angl])
fix_model FIX_MODEL: Add useful fields to a model
mk_grid_c2f MK_GRID_C2F - calculate a coarse2fine mapping for grid coarse models.
mk_tet_c2f MK_TET_C2F - calculate a coarse2fine mapping for two tet-based models.
mk_tri_c2f MK_TRI_C2F
calc_noise_figure CALC_NOISE_FIGURE: calculate the noise amplification (NF) of an algorithm
test_performance TEST_PERFORMANCE: test of difference reconstruction algorithms
test_performance_img TEST_PERFORMANCE: test of difference reconstruction algorithms
SOURCE CODE
function VOL = get_elem_volume(fwd_model, map_node)
% GET_ELEM_VOLUME: VOL = get_elem_volume(fwd_model, map_node)
% Calculate volume (or area) of each element in model
%
% If the model has a 'coarse2fine' element, then the
% returned VOL applies to the coarse matrix
%
% if map_node == 1, then calculated volumes are the volume fraction for each node
% (C) 2009 Andy Adler. License: GPL version 2 or version 3
% $Id: get_elem_volume.m 4871 2015-04-10 03:11:54Z alistair_boyle $
if nargin==1; map_node= 0; end
% calculate element volume and surface area
NODE = fwd_model.nodes';
ELEM = fwd_model.elems';
[d,e]= size(ELEM);
% cashing
c_obj = {NODE, ELEM};
VOL = eidors_obj('get-cache', c_obj, 'elem_volume');
if isempty(VOL)
    VOL=zeros(e,1);
    ones_d = ones(1,d);
    d1fac = prod( 1:d-1 );
    if d > size(NODE,1)
        for i=1:e
            this_elem = NODE(:,ELEM(:,i));
            VOL(i)= abs(det([ones_d;this_elem])) / d1fac;
        end
    elseif d == 3 % 3D nodes in 2D mesh
        for i=1:e
            this_elem = NODE(:,ELEM(:,i));
            d12= det([ones_d;this_elem([1,2],:)])^2;
            d13= det([ones_d;this_elem([1,3],:)])^2;
            d23= det([ones_d;this_elem([2,3],:)])^2;
            VOL(i)= sqrt(d12 + d13 + d23 ) / d1fac;
        end
    elseif d == 2 % 3D nodes in 1D mesh (ie resistor mesh)
        for i=1:e
            this_elem = NODE(:,ELEM(:,i));
            d12= det([ones_d;this_elem([1],:)])^2;
            d13= det([ones_d;this_elem([2],:)])^2;
            d23= det([ones_d;this_elem([3],:)])^2;
            VOL(i)= sqrt(d12 + d13 + d23 ) / d1fac;
        end
    else
        error('mesh size not understood when calculating volumes')
    end
    % caching
    eidors_cache('boost_priority', -4); % low priority
    eidors_obj('set-cache', c_obj, 'elem_volume', VOL);
    eidors_cache('boost_priority', +4); % restore priority
end
if isfield(fwd_model,'coarse2fine')
   VOL= fwd_model.coarse2fine' * VOL;
end
% Calculate the mapping of each element onto the associated node
% Map(i,j) = 1/Ne if elem j has node i
if map_node
   map = sparse( ELEM, ones(d,1)*(1:e), 1/d, size(NODE,2),e);
   VOL = map * VOL;
end